#!/usr/bin/env python3
"""Original starter tune and 68-cycle speaker DDS increments (A4 = 440 Hz)."""
from pathlib import Path
import sys


def default_song():
    data = bytearray(b'P2MC' + bytes([1, 120, 16, 0]) + bytes(192))
    # Original ascending/descending exercise, not a song from the EA disks.
    data[8:24] = bytes([60, 62, 64, 65, 67, 69, 71, 72,
                        72, 71, 69, 67, 65, 64, 62, 60])
    data[72:88] = bytes([48, 0, 55, 0, 53, 0, 55, 0,
                         48, 0, 55, 0, 53, 0, 55, 48])
    data[136:] = bytes([2] * 64)
    return data


def main():
    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)
    values = [round(440 * 2 ** ((note - 69) / 12) * 65536 * 68 / 1020484)
              for note in range(36, 84)]
    (out / 'pitches.h').write_text(
        '/* Generated by tools/assets.py; 68 CPU cycles per sample. */\n'
        'static const unsigned increments[48] = {\n' +
        ', '.join(map(str, values)) + '\n};\n')
    (out / 'song.bin').write_bytes(default_song())


if __name__ == '__main__':
    main()
