/* GPL-3.0. Fixed camera, precomputed perspective for an HGR ground plane. */
#ifndef A2_PERSPECTIVE_H
#define A2_PERSPECTIVE_H

/* Generated by dev/tools/perspective.py. Zero scale means unity (256/256).
 * All tables are borrowed, immutable and valid for rows entries (1..192).
 * Each shift is 0..279 and each screen_y is 0..191. Valid camera tables
 * keep shift + floor(279*scale/256) <= 279, treating zero scale as unity.
 */
typedef struct {
    const unsigned char *scale;
    const unsigned *shift;
    const unsigned char *screen_y;
    unsigned char rows;
} a2_perspective_t;

typedef struct {
    unsigned x;
    unsigned char y;
} a2_projected_t;

/* x=0..279, y=0..rows-1. Returns 1 on success, otherwise 0, leaving
 * *out untouched. Null pointers and projected coordinates outside HGR
 * are rejected. No allocation, graphics state, IRQ or bank changes.
 * cc65 scratch is shared: call outside IRQs, with D=0 and main RAM/ZP.
 */
unsigned char __fastcall__ a2_perspective_project(
    const a2_perspective_t *camera, unsigned x, unsigned char y,
    a2_projected_t *out);

#endif
