PERSPECTIVE_SRCS := $(PERSPECTIVE)/perspective.c
PERSPECTIVE_INCS := -I $(PERSPECTIVE)
PERSPECTIVE_HEADERS := $(PERSPECTIVE)/perspective.h
PERSPECTIVE_CORRIDOR_INCS := -I $(PERSPECTIVE)
PERSPECTIVE_CORRIDOR_DEPS := $(PERSPECTIVE)/corridor.asm $(PERSPECTIVE)/corridor.h
