; ============================================================================
; chess_cc65_pieces.asm  --  cc65-Chess Apple II piece bitmaps (HGR).
; Generated by tools/build_cc65_chess_pieces.py from chess_cc65_pieces.bin.
; DO NOT EDIT BY HAND -- rerun the generator instead.
; ----------------------------------------------------------------------------
; Art: Frank Gebhart (1980s).  Apple II HGR port: Oliver Schmidt (2020).
; From Stefan Wessels' cc65-Chess (github.com/StewBC/cc65-Chess).
; 6 pieces x 2 variants x 22 rows x 3 bytes.  bit 0 = leftmost pixel, bit 7
; clear (monochrome -- colour is applied by the copy/invert ROP at blit time).
; Piece index 0..5 = ROOK,KNIGHT,BISHOP,QUEEN,KING,PAWN; variant 0 = outline,
; 1 = solid.  Table index = piece_idx*2 + variant.
; ============================================================================
.export cc65_pieces, cc65_piece_lo, cc65_piece_hi

.segment "CODE"

cc65_pieces:
; rook outline (idx 0)
        .byte $00,$00,$00
        .byte $1E,$3E,$3C
        .byte $12,$22,$24
        .byte $12,$22,$24
        .byte $72,$63,$27
        .byte $02,$00,$20
        .byte $04,$00,$10
        .byte $08,$00,$08
        .byte $50,$7F,$05
        .byte $30,$00,$06
        .byte $20,$00,$02
        .byte $20,$00,$02
        .byte $20,$00,$02
        .byte $20,$00,$02
        .byte $20,$00,$02
        .byte $10,$00,$04
        .byte $08,$00,$08
        .byte $68,$7F,$0B
        .byte $04,$00,$10
        .byte $7E,$7F,$3F
        .byte $7E,$7F,$3F
        .byte $00,$00,$00
; rook solid (idx 1)
        .byte $00,$00,$00
        .byte $1E,$3E,$3C
        .byte $1E,$3E,$3C
        .byte $1E,$3E,$3C
        .byte $7E,$7F,$3F
        .byte $7E,$7F,$3F
        .byte $7C,$7F,$1F
        .byte $78,$7F,$0F
        .byte $70,$7F,$07
        .byte $10,$00,$04
        .byte $60,$7F,$03
        .byte $60,$7F,$03
        .byte $60,$7F,$03
        .byte $60,$7F,$03
        .byte $60,$7F,$03
        .byte $70,$7F,$07
        .byte $78,$7F,$0F
        .byte $78,$7F,$0F
        .byte $04,$00,$10
        .byte $7E,$7F,$3F
        .byte $7E,$7F,$3F
        .byte $00,$00,$00
; knight outline (idx 2)
        .byte $00,$00,$00
        .byte $00,$11,$00
        .byte $40,$2A,$00
        .byte $20,$48,$00
        .byte $20,$00,$01
        .byte $10,$00,$02
        .byte $10,$42,$02
        .byte $10,$40,$02
        .byte $08,$40,$05
        .byte $04,$00,$05
        .byte $02,$00,$04
        .byte $42,$07,$04
        .byte $24,$08,$0D
        .byte $18,$04,$0B
        .byte $00,$02,$12
        .byte $00,$01,$14
        .byte $40,$00,$30
        .byte $20,$00,$20
        .byte $50,$7F,$2F
        .byte $10,$00,$20
        .byte $70,$7F,$3F
        .byte $00,$00,$00
; knight solid (idx 3)
        .byte $00,$00,$00
        .byte $00,$11,$00
        .byte $40,$2A,$00
        .byte $60,$77,$00
        .byte $60,$7F,$01
        .byte $70,$7F,$03
        .byte $70,$3D,$03
        .byte $70,$3F,$03
        .byte $78,$3F,$06
        .byte $7C,$7F,$06
        .byte $7E,$7F,$07
        .byte $7E,$7F,$07
        .byte $3C,$78,$0E
        .byte $18,$7C,$0C
        .byte $00,$7E,$1D
        .byte $00,$7F,$1B
        .byte $40,$7F,$3F
        .byte $60,$7F,$3F
        .byte $10,$00,$20
        .byte $70,$7F,$3F
        .byte $70,$7F,$3F
        .byte $00,$00,$00
; bishop outline (idx 4)
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$22,$00
        .byte $00,$41,$00
        .byte $40,$08,$01
        .byte $20,$08,$02
        .byte $20,$7F,$02
        .byte $10,$08,$04
        .byte $10,$08,$04
        .byte $10,$08,$04
        .byte $20,$08,$02
        .byte $20,$00,$02
        .byte $40,$00,$01
        .byte $00,$7F,$00
        .byte $00,$41,$00
        .byte $00,$41,$00
        .byte $00,$3E,$00
        .byte $20,$00,$02
        .byte $78,$7F,$0F
        .byte $7C,$7F,$1F
        .byte $00,$00,$00
; bishop solid (idx 5)
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$3E,$00
        .byte $00,$7F,$00
        .byte $40,$77,$01
        .byte $60,$77,$03
        .byte $60,$00,$03
        .byte $70,$77,$07
        .byte $70,$77,$07
        .byte $70,$77,$07
        .byte $60,$77,$03
        .byte $60,$7F,$03
        .byte $40,$7F,$01
        .byte $00,$41,$00
        .byte $00,$7F,$00
        .byte $00,$7F,$00
        .byte $00,$3E,$00
        .byte $60,$7F,$03
        .byte $08,$00,$08
        .byte $7C,$7F,$1F
        .byte $00,$00,$00
; queen outline (idx 6)
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$22,$00
        .byte $38,$22,$0E
        .byte $44,$14,$11
        .byte $42,$22,$21
        .byte $22,$41,$22
        .byte $02,$00,$20
        .byte $22,$08,$22
        .byte $62,$1C,$23
        .byte $44,$7F,$11
        .byte $04,$7F,$10
        .byte $08,$00,$08
        .byte $08,$00,$08
        .byte $68,$7F,$0B
        .byte $10,$00,$04
        .byte $10,$00,$04
        .byte $10,$00,$04
        .byte $30,$00,$06
        .byte $60,$7F,$03
        .byte $00,$00,$00
; queen solid (idx 7)
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$3E,$00
        .byte $38,$3E,$0E
        .byte $7C,$1C,$1F
        .byte $7E,$3E,$3F
        .byte $3E,$7F,$3E
        .byte $7E,$7F,$3F
        .byte $5E,$77,$3D
        .byte $1E,$63,$3C
        .byte $3C,$00,$1E
        .byte $7C,$00,$1F
        .byte $78,$7F,$0F
        .byte $78,$7F,$0F
        .byte $18,$00,$0C
        .byte $70,$7F,$07
        .byte $70,$7F,$07
        .byte $70,$7F,$07
        .byte $70,$7F,$07
        .byte $60,$7F,$03
        .byte $00,$00,$00
; king outline (idx 8)
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$14,$00
        .byte $00,$77,$00
        .byte $00,$63,$00
        .byte $60,$14,$03
        .byte $10,$55,$04
        .byte $08,$36,$08
        .byte $04,$14,$10
        .byte $24,$22,$12
        .byte $12,$14,$24
        .byte $12,$08,$24
        .byte $22,$08,$22
        .byte $44,$00,$11
        .byte $04,$41,$10
        .byte $08,$00,$08
        .byte $48,$7F,$09
        .byte $10,$00,$04
        .byte $10,$00,$04
        .byte $30,$00,$06
        .byte $60,$7F,$03
        .byte $00,$00,$00
; king solid (idx 9)
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$14,$00
        .byte $00,$77,$00
        .byte $00,$63,$00
        .byte $60,$14,$03
        .byte $70,$55,$07
        .byte $78,$77,$0F
        .byte $7C,$63,$1F
        .byte $5C,$55,$1D
        .byte $6E,$63,$3B
        .byte $6E,$77,$3B
        .byte $5E,$7F,$3D
        .byte $3C,$7F,$1E
        .byte $7C,$3E,$1F
        .byte $78,$7F,$0F
        .byte $18,$00,$0C
        .byte $70,$7F,$07
        .byte $70,$7F,$07
        .byte $70,$7F,$07
        .byte $60,$7F,$03
        .byte $00,$00,$00
; pawn outline (idx 10)
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$22,$00
        .byte $00,$41,$00
        .byte $00,$41,$00
        .byte $00,$41,$00
        .byte $00,$22,$00
        .byte $00,$1C,$00
        .byte $00,$22,$00
        .byte $00,$22,$00
        .byte $00,$63,$00
        .byte $00,$22,$00
        .byte $00,$22,$00
        .byte $00,$7F,$00
        .byte $40,$00,$01
        .byte $60,$7F,$03
        .byte $60,$7F,$03
        .byte $00,$00,$00
; pawn solid (idx 11)
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$00,$00
        .byte $00,$1C,$00
        .byte $00,$3E,$00
        .byte $00,$7F,$00
        .byte $00,$7F,$00
        .byte $00,$7F,$00
        .byte $00,$3E,$00
        .byte $00,$1C,$00
        .byte $00,$3E,$00
        .byte $00,$3E,$00
        .byte $00,$7F,$00
        .byte $00,$3E,$00
        .byte $00,$3E,$00
        .byte $00,$7F,$00
        .byte $40,$00,$01
        .byte $60,$7F,$03
        .byte $60,$7F,$03
        .byte $00,$00,$00

cc65_piece_lo:
        .byte <(cc65_pieces+0), <(cc65_pieces+66), <(cc65_pieces+132), <(cc65_pieces+198), <(cc65_pieces+264), <(cc65_pieces+330), <(cc65_pieces+396), <(cc65_pieces+462), <(cc65_pieces+528), <(cc65_pieces+594), <(cc65_pieces+660), <(cc65_pieces+726)
cc65_piece_hi:
        .byte >(cc65_pieces+0), >(cc65_pieces+66), >(cc65_pieces+132), >(cc65_pieces+198), >(cc65_pieces+264), >(cc65_pieces+330), >(cc65_pieces+396), >(cc65_pieces+462), >(cc65_pieces+528), >(cc65_pieces+594), >(cc65_pieces+660), >(cc65_pieces+726)
