#!/usr/bin/env python3
"""Keep the renderer, physics and hit tables on the same screen geometry."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]/'src'
values=dict((k,int(v)) for k,v in re.findall(r'^#define (CB_\w+) (\d+)$',(root/'layout.h').read_text(),re.M))
assert values['CB_GRID_END']==values['CB_TILE_TOP']+7*12+8
assert values['CB_LOST_Y']<=187 and values['CB_PAD_Y']+4<192
def write(name,content):
    p=root/name
    if not p.exists() or p.read_text()!=content:p.write_text(content)
write('layout.inc','; Generated from layout.h. GPL-3.0.\n'+''.join(f'{k} = {v}\n' for k,v in values.items()))
cols=[(x-5)//11 if 5<=x<137 and (x-5)%11<9 else 255 for x in range(140)]
top=values['CB_TILE_TOP']
rows=[((y-top)//12)*12 if top<=y<top+96 and (y-top)%12<8 else 255 for y in range(192)]
write('collision_tables.h','/* Generated by tools/generate_layout.py. GPL-3.0. */\n'+''.join(f'const unsigned char {name}[{len(data)}]={{'+','.join(map(str,data))+'};\n' for name,data in [('cell_col',cols),('cell_row',rows)]))
