#!/usr/bin/env python3
"""Emit cached sprite masks/ink for render.s (round 4-pixel sprites and the
shaded piercing ball), and the background tiles and enemy masks of the $0800
table image.

DHGR colour C sets dot D when bit D%4 of rot(C) is set (render.s patterns).
A visible colour cell starts one dot after the 4-dot pixel window used by
the rectangle masks, so per-pixel colours are laid out with that shift.
Preserve masks keep bit 7 (Chat Mauve colour bytes)."""
from pathlib import Path
rot = lambda c: ((c >> 1) | (c << 3)) & 15
CELL_SHIFT = 1

def dots(phase, pixels):
    m = 0
    for i in pixels:
        m |= 0xF << (4 * i)
    m <<= phase
    return [(m >> (7 * b)) & 0x7F for b in range(4)]

def preserve(phase, pixels):
    return [(~v & 0x7F) | 0x80 for v in dots(phase, pixels)]

def ink(x, colours):
    bx, out = (4 * x) // 7, []
    for b in range(4):
        v = 0
        for k in range(7):
            d = 7 * (bx + b) + k
            i = min(max((d - CELL_SHIFT) // 4 - x, 0), 3)
            if colours[i] is not None and rot(colours[i]) >> (d % 4) & 1:
                v |= 1 << k
        out.append(v)
    return out

def rows(name, data):
    return [name + ':'] + ['.byte ' + ','.join(map(str, r)) for r in data]

out = ['; Generated by tools/generate_sprite_tables.py. GPL-3.0.',
       '; Round 4-pixel sprites (piercing ball, enemies): body then tip',
       '; (pixels 1-2) preserve masks, per x mod 7.']
out += rows('round4_masks', [preserve((4 * m) % 7, [0, 1, 2, 3]) + preserve((4 * m) % 7, [1, 2]) for m in range(7)])
out += ['; Piercing ball ink per x mod 28 (dot and colour phase together): body',
        '; pink, red, red, purple from left to right; tips pink then red.']
body, tip = [11, 1, 1, 3], [None, 11, 1, None]
# Not clipped to the pixel windows: the shifted cells end one dot later, and
# the save-under restores whole bytes.
out += rows('red_ball_ink', [ink(x, body) + ink(x, tip) for x in range(28)])
path = Path(__file__).resolve().parents[1] / 'src' / 'sprite_tables.inc'
text = '\n'.join(out) + '\n'
if not path.exists() or path.read_text() != text:
    path.write_text(text)

# Backgrounds, one per decade from level 11: tiles of 7 colour pixels (28
# dots, 4 bytes: the colour phase repeats) by 8 lines, dark colours only.
# Bytes keep bit 7 (Chat Mauve colour). Row r, byte column c: tile[r*4+c%4].
PALETTE = {'.': 0, 'b': 2, 'g': 4, 'k': 5, 'r': 8, 'p': 3, 'm': 1}
TILES = [
    ('STARS', ['.......', '...k...', '.......', '.......', 'b......', '.......', '....b..', '.......']),
    ('GRID', ['b.b.b.b', '.......', 'b......', '.......', 'b......', '.......', 'b......', '.......']),
    ('HATCH', ['g......', '.g.....', '..g....', '...g...', '....g..', '.....g.', '......g', '.......']),
    ('BRICKWORK', ['rrrrrrr', '...r...', '...r...', '...r...', 'rrrrrrr', 'r......', 'r......', 'r......']),
    ('DIAMONDS', ['...b...', '..b.b..', '.b...b.', 'b.....b', '.b...b.', '..b.b..', '...b...', '.......']),
    ('CROSSES', ['.......', '...p...', '..ppp..', '...p...', '.......', '.......', '.......', '.......']),
]

def tile_row(art):
    out = []
    for b in range(4):
        v = 0
        for k in range(7):
            d = 7 * b + k
            colour = PALETTE[art[((d - CELL_SHIFT) // 4) % 7]]
            if rot(colour) >> (d % 4) & 1:
                v |= 1 << k
        out.append(v | 0x80)
    return out

bg = ['; Generated by tools/generate_sprite_tables.py. GPL-3.0.',
      '; Background tiles for levels 1-10, 11-20, ... (' + ', '.join(n for n, _ in TILES) + ').',
      'bg_tiles:']
for name, art in TILES:
    assert len(art) == 8 and all(len(r) == 7 for r in art), name
    bg += ['.byte ' + ','.join(map(str, tile_row(r))) for r in art]
# Enemy masks also live in the $0800 image (main RAM is full).
bg += ['; Enemy spools: narrow core (pixels 1-2) then full bars (0-3).']
bg += rows('spool_masks', [preserve((4 * m) % 7, [1, 2]) + preserve((4 * m) % 7, [0, 1, 2, 3]) for m in range(7)])
path = Path(__file__).resolve().parents[1] / 'src' / 'bg_tiles.inc'
text = '\n'.join(bg) + '\n'
if not path.exists() or path.read_text() != text:
    path.write_text(text)
