#!/usr/bin/env python3
"""Emit the Beautiful Boot text font for DHGR: each HGR dot becomes two DHGR dots.

Its strokes are at least two HGR dots wide, i.e. four DHGR dots: a full NTSC
colour cycle, hence white on a colour monitor, while glyphs keep 280-dot detail.
"""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
source = (root.parent / 'dev/lib/hgrc/hgr_bbfont.inc').read_text()
glyphs = [int(v, 16) for v in re.findall(r'0x([0-9A-Fa-f]{2})', re.sub(r'/\*.*?\*/', '', source, flags=re.S))]
FIRST, COUNT, ROWS = 32, 64, 8
# The eighth row is blank in every glyph used here (no descenders).
HEIGHT = 7
assert len(glyphs) >= COUNT * ROWS and max(glyphs) < 128
out = ['; Generated by tools/generate_fine_font.py from dev/lib/hgrc/hgr_bbfont.inc.',
       '; Beautiful Boot font: Michael Pohoreski. GPL-3.0.',
       f'FINE_FIRST = {FIRST}', f'FINE_COUNT = {COUNT}', f'FINE_HEIGHT = {HEIGHT}',
       '; Row-major planes: glyph row R of character C is fine_font+R*COUNT+C-FIRST.',
       '.ifndef FINE_FONT_CONSTANTS_ONLY', 'fine_font:']
for r in range(HEIGHT):
    plane = [glyphs[c * ROWS + r] for c in range(COUNT)]
    for i in range(0, COUNT, 16):
        out.append('.byte ' + ','.join(map(str, plane[i:i + 16])))
out.append('.endif')
path = root / 'src' / 'fine_font.inc'
text = '\n'.join(out) + '\n'
if not path.exists() or path.read_text() != text:
    path.write_text(text)
