#!/usr/bin/env python3
"""Emit the Beautiful Boot text font for DHGR: each HGR dot becomes two DHGR dots.

Its strokes are at least two HGR dots wide, i.e. four DHGR dots: a full NTSC
colour cycle, hence white on a colour monitor, while glyphs keep 280-dot detail.
"""
from pathlib import Path
import sys
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root.parent / 'dev/tools'))
from fonts import glyph, write_if_changed
FIRST, COUNT = 32, 64
# The eighth row is blank in every glyph used here (no descenders).
HEIGHT = 7
out = ['; Generated by tools/generate_fine_font.py from the Beautiful Boot font (dev/lib/font).',
       '; Beautiful Boot font: Michael Pohoreski. GPL-3.0.',
       f'FINE_FIRST = {FIRST}', f'FINE_COUNT = {COUNT}', f'FINE_HEIGHT = {HEIGHT}',
       '; Row-major planes: glyph row R of character C is fine_font+R*COUNT+C-FIRST.',
       '.ifndef FINE_FONT_CONSTANTS_ONLY', 'fine_font:']
for r in range(HEIGHT):
    plane = [glyph(FIRST + c)[r] for c in range(COUNT)]
    for i in range(0, COUNT, 16):
        out.append('.byte ' + ','.join(map(str, plane[i:i + 16])))
out.append('.endif')
write_if_changed(root / 'src' / 'fine_font.inc', '\n'.join(out) + '\n')
