#!/usr/bin/env python3
"""Pack src/levels.txt for the auxiliary-RAM level bank.

levels.txt: ';' comment lines; per level a name line (1-10 letters) then 8 rows
of 12 tiles: '.' empty, '1'-'3' hits, '#' steel. Every hit tile must be
reachable from below through non-steel tiles, and boards must be distinct.

Output build/levels.bin (copied by CHROMA.SYS to AUX $0A00): 48 bytes per
board, two tiles per byte (low nibble first, 15 = steel), then the names,
right-aligned on 10 cells. src/levels.inc gives the layout; layout.h CB_LEVELS gives the count."""
from pathlib import Path
import sys
root = Path(__file__).resolve().parents[1]
VALUES = {'.': 0, '1': 1, '2': 2, '3': 3, '#': 255}

def load(path=root / 'src' / 'levels.txt'):
    lines = [l.rstrip() for l in path.read_text().split('\n') if not l.startswith(';')]
    levels, i = [], 0
    while i < len(lines):
        if not lines[i]:
            i += 1
            continue
        name, rows = lines[i], lines[i + 1:i + 9]
        assert name.isalpha() and name.isupper() and len(name) <= 10, name
        assert len(rows) == 8 and all(len(r) == 12 and set(r) <= set(VALUES) for r in rows), name
        levels.append((name, [VALUES[c] for r in rows for c in r]))
        i += 9
    return levels

def count():
    import re
    return int(re.search(r'^#define CB_LEVELS (\d+)$', (root / 'src' / 'layout.h').read_text(), re.M)[1])

def check(levels):
    n = count()
    assert len(levels) == n, len(levels)
    assert len({name for name, _ in levels}) == n and len({tuple(b) for _, b in levels}) == n
    for name, board in levels:
        assert any(0 < v < 255 for v in board), name
        seen = {i for i in range(84, 96) if board[i] != 255}
        pending = list(seen)
        while pending:
            i = pending.pop(); x, y = i % 12, i // 12
            for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
                n = ny * 12 + nx
                if 0 <= nx < 12 and 0 <= ny < 8 and n not in seen and board[n] != 255:
                    seen.add(n); pending.append(n)
        sealed = [i for i, v in enumerate(board) if 0 < v < 255 and i not in seen]
        assert not sealed, (name, 'steel seals', sealed)

if __name__ == '__main__':
    levels = load(); check(levels)
    nib = lambda v: 15 if v == 255 else v
    data = bytearray()
    for _, b in levels:
        data += bytes(nib(b[i]) | nib(b[i + 1]) << 4 for i in range(0, 96, 2))
    for n, _ in levels:
        data += n.rjust(10).encode()
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else root / 'build' / 'levels.bin'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(data)
    inc = ('; Generated by tools/pack_levels.py. GPL-3.0.\n'
           'LEVELS_AUX = $0A00\nLEVEL_BYTES = 48\n'
           f'LEVEL_NAMES = LEVELS_AUX+{48 * len(levels)}\nLEVELS_SIZE = {len(data)}\n')
    p = root / 'src' / 'levels.inc'
    if not p.exists() or p.read_text() != inc:
        p.write_text(inc)
