#!/usr/bin/env python3
"""gentables.py: lookup tables of src/wild.s (ca65 has no floating point).

sin_lo/sin_hi: sin(i * 90 / 140) * 256 for i = 0..140 (8.8 ray steps).
col_be/col_bo: HGR byte of the even / odd pixel of screen column 0..139.
col_me/col_mo: and-mask that clears that pixel.
Second output: rowtab.inc, the screen row of each threshold increment.
"""
import math, sys

sinq = [round(256 * math.sin(i * math.pi / 2 / 140)) for i in range(141)]
rows = ['; generated by tools/gentables.py']


def table(name, values):
    rows.append(f'{name}:')
    for k in range(0, len(values), 16):
        rows.append('        .byte   ' + ', '.join(f'${v:02X}' for v in values[k:k + 16]))


table('sin_lo', [v & 255 for v in sinq])
table('sin_hi', [v >> 8 for v in sinq])
table('col_be', [(2 * c) // 7 for c in range(140)])
table('col_bo', [(2 * c + 1) // 7 for c in range(140)])
table('col_me', [0xFF ^ (1 << ((2 * c) % 7)) for c in range(140)])
# div_lo/div_hi: DIVTAB ($4000) row of divisor n = 0..128 (rows n = 2..127
# hold n bytes each; n = 0, 1 point at the first row; n = 128 is patched to
# the `twice` table by src/wild.s).
base, rowaddr = 0x4000, []
for n in range(129):
    rowaddr.append(base if n < 2 else 0x4000 + (n - 1) * n // 2 - 1)
table('div_lo', [a & 255 for a in rowaddr])
table('div_hi', [a >> 8 for a in rowaddr])
table('col_mo', [0xFF ^ (1 << ((2 * c + 1) % 7)) for c in range(140)])
open(sys.argv[1], 'w').write('\n'.join(rows) + '\n')

# rowtab.inc: screen row of tinc, 95 - ((3 * tinc) >> 4), or $FF below row
# 159 (same rule as tools/view_ref.py), in four pages indexed by |tinc| bits:
# row_p0[q] tinc = q, row_p1[q] tinc = 256 + q, row_n0[q] tinc = -q,
# row_n1[q] tinc = -(256 + q).
def row(tinc):
    off = (3 * tinc) >> 4
    return 95 - off if off >= -64 else 0xFF


rows = ['; generated by tools/gentables.py']
for name, f in (('row_p0', lambda q: q), ('row_p1', lambda q: 256 + q),
                ('row_n0', lambda q: -q), ('row_n1', lambda q: -256 - q)):
    vals = [row(f(q)) for q in range(256)]
    rows.append(f'{name}:')
    for k in range(0, 256, 16):
        rows.append('        .byte   ' + ', '.join(f'${v:02X}' for v in vals[k:k + 16]))
open(sys.argv[2], 'w').write('\n'.join(rows) + '\n')
