#!/usr/bin/env python3
"""Reproduce the checked-in fixed-rate ca65 PWM player using a host C compiler."""
import argparse
import os
from pathlib import Path
import shlex
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
DEFAULT = HERE.parents[1] / 'lib/audio/sample_player.s'


def generate(compiler=None):
    with tempfile.TemporaryDirectory(prefix='pom2-pwm-generator-') as temp:
        binary = Path(temp) / 'generate'
        subprocess.run([*shlex.split(compiler or os.environ.get('CC', 'cc')),
                        '-std=c99', '-O2', '-Wall', '-Wextra', '-o', str(binary),
                        str(HERE / 'gen_sample_player.c')], check=True)
        result = subprocess.run([str(binary), '8000', 'AUDIOCODE'],
                                check=True, capture_output=True, text=True)
    return ('; Colin Leroy-Mira, 2025 — GPL-3.0-or-later.\n'
            '; Adapted for pom2games; see dev/tools/audio/NOTICE.txt.\n'
            '; Generated by dev/tools/audio/generate_player.py.\n' + result.stdout.rstrip() + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=DEFAULT)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate()
    if args.check:
        if args.out.read_text() != content:
            parser.error(f'{args.out} differs from generator output')
    else:
        args.out.write_text(content)


if __name__ == '__main__':
    main()
