#!/usr/bin/env python3
"""PCM WAV -> fixed nominal 8 kHz Apple II PWM codes, ca65 source + C header."""
import argparse
import math
from pathlib import Path
import re
import wave

RATE = 8000
LEVELS = 48
BIAS = 0x32
END = BIAS + LEVELS * 2


def read_pcm(path):
    with wave.open(str(path), 'rb') as wav:
        if wav.getcomptype() != 'NONE':
            raise ValueError('only uncompressed PCM WAV is supported')
        width, channels, rate = wav.getsampwidth(), wav.getnchannels(), wav.getframerate()
        if width not in (1, 2, 3, 4) or channels < 1 or rate < 1:
            raise ValueError('PCM must have 8, 16, 24 or 32 bits and a positive rate')
        frames = wav.getnframes()
        raw = wav.readframes(frames)
    if len(raw) != frames * channels * width:
        raise ValueError('truncated WAV data')
    values = []
    full_scale = 1 << (8 * width - 1)
    for start in range(0, len(raw), channels * width):
        total = 0
        for channel in range(channels):
            pos = start + channel * width
            value = int.from_bytes(raw[pos:pos+width], 'little', signed=width != 1)
            total += value - 128 if width == 1 else value
        values.append(total / (channels * full_scale))
    return values, rate


def resample(values, source_rate):
    count = len(values) * RATE // source_rate
    if not count:
        return []
    if source_rate <= RATE:
        result = []
        for i in range(count):
            pos = i * source_rate / RATE
            left = int(pos)
            right = min(left + 1, len(values) - 1)
            result.append(values[left] + (values[right] - values[left]) * (pos - left))
        return result
    # Area averaging before decimation limits aliasing, using prefix sums.
    sums = [0.0]
    for value in values:
        sums.append(sums[-1] + value)

    def integral(pos):
        index = min(int(pos), len(values))
        return sums[index] + ((pos - index) * values[index] if index < len(values) else 0)

    step = source_rate / RATE
    return [(integral((i+1)*step) - integral(i*step)) / step for i in range(count)]


def encode(values, fade_ms=2):
    if not math.isfinite(fade_ms) or fade_ms < 0:
        raise ValueError('fade-ms must be finite and nonnegative')
    fade = min(int(fade_ms * RATE / 1000), len(values) // 2)
    out = bytearray()
    for i, value in enumerate(values):
        if fade:
            value *= min(1.0, i / fade, (len(values) - 1 - i) / fade)
        value = max(-1.0, min(1.0, value))
        level = int((value + 1) * (LEVELS - 1) / 2 + 0.5)
        out.append(BIAS + 2 * level)
    out.append(END)
    if len(out) > 65535:
        raise ValueError('encoded clip including terminator exceeds 65535 bytes; split it')
    return bytes(out)


def emit(data, name):
    if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', name):
        raise ValueError('name must be a C identifier starting with a letter')
    lines = ['; Generated by dev/tools/audio/pack_wav.py; nominal 8000 Hz.',
             f'.export _{name}', '.segment "RODATA"', f'_{name}:']
    for i in range(0, len(data), 16):
        lines.append('    .byte ' + ', '.join(f'${value:02X}' for value in data[i:i+16]))
    header = (f'/* Generated PWM sample: {len(data)-1} samples, nominal 8000 Hz. */\n'
              f'extern const unsigned char {name}[{len(data)}];\n')
    return '\n'.join(lines) + '\n', header


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('wav', type=Path)
    parser.add_argument('--out', type=Path, required=True, help='output stem (.s and .h)')
    parser.add_argument('--name', default='sample')
    parser.add_argument('--fade-ms', type=float, default=2.0)
    args = parser.parse_args()
    try:
        values, rate = read_pcm(args.wav)
        assembly, header = emit(encode(resample(values, rate), args.fade_ms), args.name)
    except (ValueError, OSError, wave.Error) as error:
        parser.error(str(error))
    args.out.with_suffix('.s').write_text(assembly)
    args.out.with_suffix('.h').write_text(header)


if __name__ == '__main__':
    main()
