/* GPL-3.0. Execute real projection instructions on the portable 6502 core.
 * Built by corridor_projection.py/test_corridor.py with a labels header.
 */
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cpu6502.h"
#include "corridor_labels.h"

static uint8_t ram[65536];
static Cpu cpu;
static uint64_t minimum[3]={UINT64_MAX,UINT64_MAX,UINT64_MAX}, maximum[3], total[3];
static unsigned count[3];

static uint8_t read_byte(void *ctx, uint16_t address)
{
    (void)ctx;
    return ram[address];
}
static void write_byte(void *ctx, uint16_t address, uint8_t value)
{
    (void)ctx;
    assert(address<0xc000); /* no softswitch or bank writes */
    ram[address]=value;
}
static void load(const char *file, unsigned base, unsigned capacity)
{
    FILE *stream=fopen(file,"rb");
    long size;
    assert(stream);
    assert(!fseek(stream,0,SEEK_END)); size=ftell(stream); rewind(stream);
    assert(size>0 && (unsigned long)size<=capacity);
    assert(fread(ram+base,1,(size_t)size,stream)==(size_t)size);
    fclose(stream);
}
static void call(unsigned address, unsigned value, unsigned family, unsigned masked)
{
    unsigned steps=0;
    cpu.pc=(uint16_t)address;cpu.a=(uint8_t)value;cpu.x=(uint8_t)(value>>8);
    cpu.y=0x5a;cpu.s=0xfd;cpu.p=FU|(masked?FI:0);cpu.cycles=6; /* JSR cost */
    ram[0x1fe]=0xff;ram[0x1ff]=3; /* RTS -> $0400 */
    while(cpu.pc!=0x0400 && steps++<1000) cpu_step(&cpu);
    assert(cpu.pc==0x0400 && cpu.s==0xff && (cpu.p&FI)==(masked?FI:0));
    if(cpu.cycles<minimum[family]) minimum[family]=cpu.cycles;
    if(cpu.cycles>maximum[family]) maximum[family]=cpu.cycles;
    total[family]+=cpu.cycles;count[family]++;
}
int main(int argc, char **argv)
{
    unsigned distance, index, axis, span, value, masked;
    const unsigned centers[2]={CENTER_X,CENTER_Y};
    const unsigned states[2]={STATE_SX,STATE_SY}, origins[2]={STATE_LEFT,STATE_TOP};
    const unsigned functions[2]={PROJECT_X,PROJECT_Y};
    uint8_t initial_x[256], initial_y[256];
    assert(argc==2 || argc==3);
    load(argv[1],0x6000,0x3600);
    if(argc==3) load(argv[2],0x11e0,0xe20);
    memcpy(initial_x,ram+TABLE_X,256);memcpy(initial_y,ram+TABLE_Y,256);
    cpu.read=read_byte;cpu.write=write_byte;
    for(masked=0;masked<2;++masked) {
        for(distance=0;distance<65536;++distance) {
            index=distance/(1u<<DEPTH_SHIFT);
            if(index>255)index=255;
            call(SELECT_DEPTH,distance,0,masked);
            assert(ram[STATE_DEPTH]==index);
            assert(ram[STATE_SX]==initial_x[index] && ram[STATE_SY]==initial_y[index]);
            assert(ram[STATE_LEFT]==CENTER_X-initial_x[index]/2);
            assert(ram[STATE_TOP]==CENTER_Y-initial_y[index]/2);
        }
        for(axis=0;axis<2;++axis) {
            /* Test every admissible span, not only those generated by the
             * current camera. Keeps custom camera tables interchangeable.
             */
            for(span=0;span<256;++span) {
                int origin=(int)centers[axis]-(int)(span/2);
                if(origin<0 || origin+(int)(127*span/128)>255)continue;
                ram[states[axis]]=(uint8_t)span;ram[origins[axis]]=(uint8_t)origin;
                for(value=0;value<128;++value) {
                    call(functions[axis],value,axis+1,masked);
                    assert(cpu.a==origin+value*span/128 && cpu.x==0 && cpu.y==0x5a);
                }
            }
        }
    }
    assert(!memcmp(initial_x,ram+TABLE_X,256) && !memcmp(initial_y,ram+TABLE_Y,256));
    for(axis=0;axis<3;++axis)
        printf("%u %llu %llu %llu %u\n",axis,(unsigned long long)minimum[axis],
               (unsigned long long)maximum[axis],(unsigned long long)total[axis],count[axis]);
    return 0;
}
