#!/usr/bin/env python3
"""The MICRO-SOKOBAN HUD/title font: a Beautiful Boot subset indexed by glyph.

Strings in the game are glyph indices, not ASCII (GSTR in the generated
include), so the resident only carries the 45 glyphs it prints. The glyphs
come from the shared master (dev/lib/font, via dev/tools/fonts.py); the five
in EXTRA were drawn for the Apple II port in the same 6 px / 2 px-stroke
style and live here.

    python3 tools/hud_font.py        # rewrites src/bbfont_subset.inc if needed
    from hud_font import ORDER       # glyph index = ORDER.index(char)
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'dev/tools'))
from fonts import glyph, write_if_changed

# Glyph order = glyph index. Digits first so '0'..'9' map to 0..9.
ORDER = "0123456789MV:SOKBANPREL GHTDYIUQWZCX()JF+-/?."
# Port additions, not in the Beautiful Boot master.
EXTRA = {
    'F': (0x3F, 0x3F, 0x03, 0x1F, 0x03, 0x03, 0x03, 0x00),
    '+': (0x00, 0x0C, 0x0C, 0x3F, 0x3F, 0x0C, 0x0C, 0x00),
    '-': (0x00, 0x00, 0x00, 0x3F, 0x3F, 0x00, 0x00, 0x00),
    '/': (0x30, 0x30, 0x18, 0x0C, 0x06, 0x03, 0x03, 0x00),
    '.': (0x00, 0x00, 0x00, 0x00, 0x00, 0x0C, 0x0C, 0x00),
}
NAMES = {' ': 'SPACE', ':': 'COLON', '(': 'LPAREN', ')': 'RPAREN', '+': 'PLUS',
         '-': 'MINUS', '/': 'SLASH', '?': 'QUEST', '.': 'DOT'}


def rows(ch):
    return EXTRA.get(ch) or glyph(ch)


def main():
    out = ['; GENERATED by tools/hud_font.py -- edit ORDER / EXTRA there, not this file.',
           '; MICRO-SOKOBAN HUD/title font: Beautiful Boot glyphs (dev/lib/font, bit 0 =',
           '; left pixel, 8 rows top->bottom) in game glyph order, plus the port additions',
           '; F + - / . drawn in the same style. Strings are glyph indices (GSTR).',
           '',
           'BBFONT_MICRO_SOKOBAN_BYTES_PER_GLYPH = 8',
           'BBFONT_MICRO_SOKOBAN_GLYPH_COUNT     = %d' % len(ORDER),
           '',
           'HGR_MicroSokoban_bbfont:']
    for i, ch in enumerate(ORDER):
        label = 'space' if ch == ' ' else "'%s'" % ch
        extra = ' (port addition)' if ch in EXTRA else ''
        out.append('        .byte %s  ; %d %s%s' % (', '.join('$%02X' % b for b in rows(ch)), i, label, extra))
    out += ['',
            '.assert (* - HGR_MicroSokoban_bbfont) = (BBFONT_MICRO_SOKOBAN_GLYPH_COUNT * BBFONT_MICRO_SOKOBAN_BYTES_PER_GLYPH), error',
            '',
            '; --- Glyph indices, and GSTR "TEXT": the text as glyph indices + $FF ---']
    for i, ch in enumerate(ORDER):
        if ch.isdigit():
            continue
        out.append('G_%s = %d' % (NAMES.get(ch, ch), i))
    out += ['', '.macro GSTR str', '.repeat .strlen(str), I',
            "  .if .strat(str, I) >= '0' .and .strat(str, I) <= '9'",
            "        .byte .strat(str, I) - '0'"]
    for ch, name in NAMES.items():
        out.append("  .elseif .strat(str, I) = '%s'" % ch)
        out.append('        .byte G_%s' % name)
    out += ['  .else', '        .byte .ident(.sprintf("G_%c", .strat(str, I)))', '  .endif',
            '.endrepeat', '        .byte $FF', '.endmacro', '']
    write_if_changed(ROOT / 'micro-sokoban/src/bbfont_subset.inc', '\n'.join(out))


if __name__ == '__main__':
    main()
