#!/usr/bin/env python3
"""Pack TMS 16x16 patterns into byte-aligned HGR rows at build time.

No vertical duplication: metadata describes repeated rows for the runtime.
Downsampling takes the maximum over each source block to retain silhouettes.
Usage: pack_hgr_sprites.py --out sprites.inc --prefix ship source.asm:label ...
Output order: each source, then sizes 8,16,32,64,4,2,1 pixels.
"""
import argparse
import re
from pathlib import Path

SCALES = (0, 1, 2, 4, -1, -2, -3)

def pattern(path, label):
    source = path.read_text().split(label + ":", 1)[1]
    values = []
    for line in source.splitlines():
        line = line.split(";", 1)[0]
        if re.match(r"^\w+:", line):
            break
        if ".byte" in line:
            values.extend(int(v, 16) for v in re.findall(r"\$([0-9a-fA-F]{2})", line))
        if len(values) == 32:
            return values
    raise ValueError(f"{path}: {label} is not a 16x16 pattern")


def packed(pattern, scale):
    if len(pattern) != 32 or any(not 0 <= value <= 255 for value in pattern):
        raise ValueError("expected a 32-byte TMS 16x16 pattern")
    if scale not in SCALES:
        raise ValueError("unsupported sprite scale")
    pixels = [[(pattern[y + (x // 8) * 16] >> (7 - x % 8)) & 1
               for x in range(16)] for y in range(16)]
    if scale <= 0:
        factor = 2 if scale == 0 else 2 ** (1 - scale)
        rows = [[max(pixels[y + dy][x + dx] for dy in range(factor) for dx in range(factor))
                 for x in range(0, 16, factor)] for y in range(0, 16, factor)]
    else:
        rows = [[pixel for pixel in row for _ in range(scale)] for row in pixels]
    return [sum(bit << n for n, bit in enumerate(row[x:x + 7]))
            for row in rows for x in range(0, len(row), 7)]


def emit(sources, prefix="packed_sprite"):
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", prefix):
        raise ValueError("prefix must be a ca65 identifier")
    lines = ["; Generated by dev/tools/assets/pack_hgr_sprites.py; source art retains its licence."]
    names = []
    for kind, (file, label) in enumerate(sources):
        pat = pattern(Path(file), label)
        for size, scale in enumerate(SCALES):
            name = f"{prefix}_{kind}_{size}"
            names.append(name)
            lines.append(name + ":")
            data = packed(pat, scale)
            for start in range(0, len(data), 16):
                lines.append("    .byte " + ",".join(f"${v:02X}" for v in data[start:start + 16]))
    lines.extend([prefix + "_lo: .byte " + ",".join("<" + n for n in names),
                  prefix + "_hi: .byte " + ",".join(">" + n for n in names)])
    # Describe the format once, independently of the number of patterns.
    for suffix, values in (
        ("width", (2,3,5,10,1,1,1)), ("height", (8,16,32,64,4,2,1)),
        ("source_rows", (8,16,16,16,4,2,1)), ("vertical", (1,1,2,4,1,1,1)),
        ("last_mask", (1,3,15,1,15,3,1))):
        lines.append(prefix + "_" + suffix + ": .byte " + ",".join(str(v) for v in values))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sources", nargs="+", help="assembly_file:pattern_label")
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--prefix", default="packed_sprite")
    args = parser.parse_args()
    sources = [s.rsplit(":", 1) for s in args.sources]
    if any(len(s) != 2 for s in sources):
        parser.error("each source must be assembly_file:pattern_label")
    args.out.write_text(emit(sources, args.prefix))


if __name__ == "__main__":
    main()
