"""Original monochrome balls, seven HGR phases and perspective lookup tables."""
import sys
import json
from pathlib import Path


def bank(name, width, height, pixel):
    stride = (width + 12) // 7
    data, masks = [], []
    for phase in range(7):
        for y in range(height):
            row = [0] * stride
            mask = [255] * stride
            for x in range(width):
                lit, cover = pixel(x, y)
                col, bit = divmod(x + phase, 7)
                if cover:
                    mask[col] &= ~(1 << bit)
                if lit:
                    row[col] |= 1 << bit
            data.extend(row)
            masks.extend(mask)
    return array(name + '_data', data) + array(name + '_mask', masks) + \
        f'const hgr_mspr_t {name} = {{{name}_data, {name}_mask, {stride}, {height}}};\n'


def array(name, values):
    rows = [','.join(str(v) for v in values[i:i + 24]) for i in range(0, len(values), 24)]
    return f'const unsigned char {name}[] = {{\n' + ',\n'.join(rows) + '\n};\n'


out = '/* Generated by tools/assets.py; GPL-3.0. */\n'
for n in (4, 6, 8):
    def pixel(x, y, n=n):
        dx, dy = 2 * x - n + 1, 2 * y - n + 1
        inside = dx * dx + dy * dy <= n * n
        # White sphere, black halo and a small dark lower-right shade.
        lit = inside and dx * dx + dy * dy <= (n - 2) ** 2
        if n == 4:
            # Twelve white pixels retain a round silhouette at long range.
            lit = inside
        if n >= 7 and x > n // 2 and y > n // 2:
            lit = lit and (x + y) % 2 == 0
        return lit, inside
    out += bank(f'ball{n}', n, n, pixel)
out += 'const hgr_mspr_t *const balls[] = {&ball4,&ball6,&ball8};\n'
out += bank('paddle', 28, 18, lambda x, y: (
    x in (1, 26) or y in (1, 16), x < 3 or x > 24 or y < 3 or y > 14))
out += array('scale_x', [252 * 32 // (32 + d) for d in range(256)])
out += array('scale_y', [148 * 32 // (32 + d) for d in range(256)])
out += array('ray_upper_y', [6+d*67//114 if d<=114 else 255 for d in range(128)])
Path(sys.argv[1]).write_text(out)

# Sparse immutable corridor backdrop: only the lit HGR bytes per scanline.
# The renderer can repair a dirty rectangle without retracing long diagonals.
rows = [bytearray(40) for _ in range(160)]
def line(x0, y0, x1, y1):
    dx, dy = abs(x1-x0), -abs(y1-y0)
    sx, sy = (1 if x0<x1 else -1), (1 if y0<y1 else -1)
    error = dx+dy
    while True:
        rows[y0][x0//7] |= 1 << (x0%7)
        if (x0,y0)==(x1,y1):
            break
        e = error*2
        if e>=dy:
            error+=dy; x0+=sx
        if e<=dx:
            error+=dx; y0+=sy
for coords in ((2,6,116,73),(254,6,140,73),(2,154,116,87),(254,154,140,87),
               (116,73,140,73),(116,87,140,87),(116,73,116,87),(140,73,140,87)):
    line(*coords)
offsets, sparse = [], []
for y in range(1, 80):
    assert rows[y] == rows[160-y], 'backdrop must be vertically symmetric'
for row in rows[:81]:
    offsets.append(len(sparse))
    for col, value in enumerate(row):
        if value:
            sparse.extend((col,value))
    sparse.append(255)
background = array('bg_offset_lo', [n&255 for n in offsets])
background += array('bg_offset_hi', [n>>8 for n in offsets])
background += array('bg_bytes', sparse)
Path(sys.argv[1]).with_name('background.h').write_text(background)
mouse = array('mouse_map_x', [8+x*112//139 for x in range(140)])
mouse += array('mouse_map_y', [12+y*104//191 for y in range(192)])
Path(sys.argv[1]).with_name('mousemap.h').write_text(mouse)

levels = json.loads((Path(__file__).resolve().parents[1] / 'levels.json').read_text())
maps = []
for level in levels:
    slots = [0]*24
    for obstacle in level['obstacles']:
        index = obstacle['z']//128-1
        width = [48,40,44,36].index(obstacle['width']) << 4
        side = {'R':1, 'L':65, 'D':128}[obstacle['kind']]
        slots[index] = side | width | obstacle['phase']
    maps.extend(slots)
data = array('level_maps', maps)
data += array('level_counts', [level['length']//128 for level in levels])
Path(sys.argv[1]).with_name('levels.h').write_text(data)
