#!/usr/bin/env python3
"""Build a byte-aligned x2 HGR title from the repository's Beautiful Boot font."""
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(root / 'dev/tools'))
from fonts import glyph, double7, write_if_changed

rows = []
for y in range(7):
    row = []
    for letter in 'ARKABREAKOUT':
        row.extend(double7(glyph(letter)[y]))
    rows.append(row)
output = '; Generated by tools/generate_title.py. Beautiful Boot, Michael Pohoreski.\ntitle_bitmap:\n'
output += ''.join('.byte ' + ','.join(f'${b:02x}' for b in row) + '\n' for row in rows)
write_if_changed(root / 'arkabreakout/src/title.inc', output)
