#!/usr/bin/env python3
"""Build a byte-aligned x2 HGR title from the repository's Beautiful Boot font."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[2]
source = root/'dev/lib/hgr/bbfont_ascii5f.inc'
font = []
for line in source.read_text().splitlines():
    if '.byte' in line:
        font.extend(int(s,16) for s in re.findall(r'\$([0-9A-Fa-f]{2})', line.split(';')[0]))
assert len(font) == 512
rows = []
for y in range(8):
    row = []
    for letter in 'ARKABREAKOUT':
        glyph = font[(ord(letter)-32)*8+y]
        doubled = sum(3 << (2*x) for x in range(7) if glyph & (1 << x))
        row.extend((doubled & 127, (doubled >> 7) & 127))
    rows.extend((row,row))
output = '; Generated by tools/generate_title.py. Beautiful Boot, Michael Pohoreski.\ntitle_bitmap:\n'
output += ''.join('.byte '+','.join(f'${b:02x}' for b in row)+'\n' for row in rows)
(root/'arkabreakout/src/title.inc').write_text(output)
