#!/usr/bin/env python3
"""Pre-shift white capsule/enemy glyphs for all seven HGR pixel alignments."""
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(root/'dev/tools'))
from fonts import glyph, write_if_changed
shapes={'cap_'+c.lower(): list(glyph(c)) for c in 'ESCDLP'}
shapes.update(enemy_coil=[28,62,99,62,28,62,0,0],enemy_tie=[65,99,119,127,119,99,65,0])
out='; Generated by tools/generate_sprites.py. GPL-3.0.\ncap_assets: .word '+','.join('cap_'+c.lower() for c in 'ESCDLP')+'\n'
for name,rows in shapes.items():
    out+=name+':\n'
    for shift in range(7):
        data=[]
        for row in rows:
            pixels=(row&127)<<shift
            data += [pixels&127,(pixels>>7)&127]
        out+='.byte '+','.join(str(b) for b in data)+'\n'
out+='enemy_assets: .word enemy_coil,enemy_tie\n'
write_if_changed(root/'arkabreakout/src/capsules.inc',out)
