#!/usr/bin/env python3
"""Beautiful Boot 8x8 font: one master, every derived table.

Master: dev/lib/font/bbfont_glyphs.inc (256 CP437 glyphs, 8 bytes each,
row 0 = top, bit 0 = leftmost pixel, bit 7 clear). Assembly programs slice
it with dev/lib/font/bbfont.inc; C programs and build tools go through this
module, so no script re-parses the table by hand.

    from fonts import bbfont, glyph, double7, write_if_changed

    python3 dev/tools/fonts.py           # regenerate the derived tables
    python3 dev/tools/fonts.py --check   # fail if a derived table drifted
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
MASTER = ROOT / 'dev/lib/font/bbfont_glyphs.inc'
C_FRAGMENT = ROOT / 'dev/lib/font/bbfont_c.inc'
DHGR_DIGITS = ROOT / 'dev/examples/dhgr/src/digits.inc'

BYTES_PER_GLYPH = 8
_cache = None


def bbfont():
    """The 2048 master bytes: glyph c occupies [c*8, c*8+8)."""
    global _cache
    if _cache is None:
        data = []
        for line in MASTER.read_text().splitlines():
            code = line.split(';')[0]
            m = re.match(r'\s*bbglyph\s+\$([0-9A-Fa-f]{2})\s*,(.*)', code)
            if not m:
                continue
            assert int(m.group(1), 16) == len(data) // BYTES_PER_GLYPH, line
            data += [int(v, 16) for v in re.findall(r'\$([0-9A-Fa-f]{2})', m.group(2))]
        assert len(data) == 256 * BYTES_PER_GLYPH, len(data)
        assert max(data) < 0x80, 'a glyph uses bit 7'
        _cache = data
    return _cache


def glyph(code):
    """The 8 rows of CP437 glyph `code` (an int or a one-character string)."""
    if isinstance(code, str):
        code = ord(code)
    return bbfont()[code * BYTES_PER_GLYPH:(code + 1) * BYTES_PER_GLYPH]


def glyphs(first, last):
    """Rows of glyphs first..last inclusive, as one flat list."""
    return bbfont()[first * BYTES_PER_GLYPH:(last + 1) * BYTES_PER_GLYPH]


def double7(row):
    """HGR x2: a 7-pixel row becomes 14 pixels in two 7-bit bytes (lo, hi)."""
    wide = sum(3 << (2 * x) for x in range(7) if row & (1 << x))
    return wide & 0x7F, (wide >> 7) & 0x7F


def dhgr_cells(row):
    """DHGR: a 7-pixel row as 7 white colour cells (4 bits each), in the four
    interleaved 7-bit bytes of a 28-dot span."""
    bits = sum(0xF << (4 * x) for x in range(7) if row & (1 << x))
    return [(bits >> (7 * k)) & 0x7F for k in range(4)]


def asm_bytes(data, per_line=8, hexa=True):
    """`.byte` lines for ca65."""
    fmt = (lambda b: '$%02X' % b) if hexa else str
    return ''.join('        .byte ' + ','.join(fmt(b) for b in data[i:i + per_line]) + '\n'
                   for i in range(0, len(data), per_line))


def write_if_changed(path, text):
    """Write `text` to `path` only if it differs (keeps make from rebuilding)."""
    path = Path(path)
    if path.exists() and path.read_text() == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return True


def c_fragment():
    lines = ['/* VERHILLE Arnaud — GPL-3.0 (see LICENSE at repository root). */',
             '/* bbfont_c.inc - GENERATED by dev/tools/fonts.py. DO NOT EDIT.',
             ' * Beautiful Boot 8x8 font, ASCII 0x20-0x7F (96 glyphs): the ASCII slice of',
             ' * dev/lib/font/bbfont_glyphs.inc. bit 0 = leftmost pixel, rows top->bottom,',
             ' * values <= 0x7F so each glyph fits HGR\'s 7 px/byte. */']
    for c in range(0x20, 0x80):
        lines.append('    ' + ','.join('0x%02X' % b for b in glyph(c)) + ',  /* 0x%02X */' % c)
    return '\n'.join(lines) + '\n'


def dhgr_digits():
    out = ['; GENERATED by dev/tools/fonts.py: decimal glyphs of the Beautiful Boot',
           '; font, each HGR dot expanded to one white DHGR colour cell.',
           '; Four interleaved 7-bit bytes per row; 8 rows per digit.']
    for c in '0123456789':
        for row in glyph(c):
            out.append('    .byte ' + ', '.join('$%02X' % b for b in dhgr_cells(row)))
    return '\n'.join(out) + '\n'


DERIVED = {C_FRAGMENT: c_fragment, DHGR_DIGITS: dhgr_digits}


def main(argv):
    check = '--check' in argv
    stale = []
    for path, make in DERIVED.items():
        text = make()
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(path)
        elif write_if_changed(path, text):
            print('wrote', path.relative_to(ROOT))
    if stale:
        sys.exit('stale font tables, run dev/tools/fonts.py: '
                 + ', '.join(str(p.relative_to(ROOT)) for p in stale))
    if check:
        print('font tables: %d derived files up to date' % len(DERIVED))


if __name__ == '__main__':
    main(sys.argv[1:])
