#!/usr/bin/env python3
"""Generate a fixed-camera HGR ground-plane projection; no target division."""
import argparse
from fractions import Fraction
from pathlib import Path
import re


def corridor_scales(span_x=252, span_y=148, focal=32, center_x=128, center_y=80):
    """Two 256-entry byte tables; depth units match PC_DEPTH_SHIFT on target."""
    focal = Fraction(focal)
    if focal <= 0:
        raise ValueError('focal must be positive')
    for span, center in ((span_x, center_x), (span_y, center_y)):
        if not 0 <= span <= 255 or not 0 <= center <= 255:
            raise ValueError('corridor spans and centers must be 0..255')
        if center - span//2 < 0 or center - span//2 + 127*span//128 > 255:
            raise ValueError('corridor span extends beyond the byte-sized screen axis')
    return ([int(span_x * focal / (focal + d)) for d in range(256)],
            [int(span_y * focal / (focal + d)) for d in range(256)])


def generate_corridor(name='corridor', **kwargs):
    if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', name):
        raise ValueError('name must be a C identifier starting with a letter')
    xs, ys = corridor_scales(**kwargs)
    lines = ['/* Generated corridor tables; GPL-3.0. Include in one C unit. */']
    for suffix, values in (('scale_x', xs), ('scale_y', ys)):
        lines.append(f'const unsigned char {name}_{suffix}[256] = {{')
        for i in range(0,256,16):
            lines.append('    ' + ', '.join(map(str,values[i:i+16])) + ',')
        lines.append('};')
    return '\n'.join(lines) + '\n'


def tables(rows=192, focal=78, center=140, horizon=31, bottom=191):
    if not 1 <= rows <= 192:
        raise ValueError('rows must be 1..192')
    focal = Fraction(focal)
    if focal <= 0 or not 0 <= center <= 279 or not 0 <= horizon < bottom <= 191:
        raise ValueError('focal > 0, center 0..279, 0 <= horizon < bottom <= 191 required')
    scales, shifts, ys = [], [], []
    for y in range(rows):
        scale = max(1, int(256 * focal / (focal + rows - 1 - y)))
        # Use the quantized scale for X centering: camera remains centered
        # to within one pixel, including the identity row (encoded as zero).
        scales.append(scale & 255)
        shifts.append(center * (256 - scale) // 256)
        ys.append(horizon + int((bottom - horizon) * focal / (focal + rows - 1 - y)))
    return scales, shifts, ys


def generate(name='camera', **kwargs):
    if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', name):
        raise ValueError('name must be a C identifier starting with a letter')
    scales, shifts, ys = tables(**kwargs)
    out = ['/* Generated by dev/tools/perspective.py; GPL-3.0. */',
           '#include "perspective.h"']
    for suffix, values, ctype in (('scale', scales, 'unsigned char'),
                                  ('shift', shifts, 'unsigned'),
                                  ('y', ys, 'unsigned char')):
        out.append(f'static const {ctype} {name}_{suffix}[] = {{')
        for i in range(0, len(values), 16):
            out.append('    ' + ', '.join(map(str, values[i:i+16])) + ',')
        out.append('};')
    out.append(f'static const a2_perspective_t {name} = {{'
               f'{name}_scale, {name}_shift, {name}_y, {len(scales)}' + '};')
    return '\n'.join(out) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, required=True)
    parser.add_argument('--name', help='default: plane camera, corridor corridor')
    parser.add_argument('--kind', choices=('plane', 'corridor'), default='plane')
    parser.add_argument('--rows', type=int, default=192)
    parser.add_argument('--focal', type=Fraction, help='default: plane 78, corridor 32')
    parser.add_argument('--center', type=int, default=140)
    parser.add_argument('--horizon', type=int, default=31)
    parser.add_argument('--bottom', type=int, default=191)
    parser.add_argument('--span-x', type=int, default=252)
    parser.add_argument('--span-y', type=int, default=148)
    parser.add_argument('--center-x', type=int, default=128)
    parser.add_argument('--center-y', type=int, default=80)
    args = parser.parse_args()
    name = args.name or ('corridor' if args.kind == 'corridor' else 'camera')
    focal = args.focal if args.focal is not None else Fraction(32 if args.kind == 'corridor' else 78)
    try:
        if args.kind == 'corridor':
            content = generate_corridor(name, span_x=args.span_x, span_y=args.span_y,
                                       focal=focal, center_x=args.center_x,
                                       center_y=args.center_y)
        else:
            content = generate(name, rows=args.rows, focal=focal,
                               center=args.center, horizon=args.horizon, bottom=args.bottom)
    except ValueError as error:
        parser.error(str(error))
    args.out.write_text(content)


if __name__ == '__main__':
    main()
