; Colin Leroy-Mira, 2025 — GPL-3.0-or-later.
; Adapted for pom2games; see dev/tools/audio/NOTICE.txt.
; Generated by dev/tools/audio/generate_player.py.
; Settings for this sound generator:
; CYCLES_PER_SEC = 1023000
; CARRIER_HZ = 16000
; SAMPLING_HZ = 8000
; DUTY_CYCLE_LENGTH = 63
; AVAIL_CYCLES = 63
; NUM_LEVELS = 48
; STEP = 1

; Adapted for pom2games: fixed rate, main RAM, D=0, nominal 1 MHz.
; Blocking, non-reentrant; IRQ mask preserved. No video/bank changes.
; A/X = encoded sample pointer. Null pointer is a no-op.
; Clobbers A/X/Y, ptr1, ptr3 and ptr4 low byte (3-byte JMP), tmp3.
; Source must end with $92, contain only even $32..$90 codes,
; and remain in main RAM without crossing $FFFF.
         .export _a2_sample_play
         .importzp ptr1, ptr3, tmp3
SPKR = $C030
target = ptr3

.segment "AUDIOCODE"
.align $100
START_SOUND_PLAYER = *
; Total cost 22 cycles
; Could be 21 but we need to fit between SPKR access at level 22
; if slower is enabled, so we waste one cycle with INC absolute.
.proc incr_pointer
         iny                         ; 2
         bne :+                      ; 4   (5)
         .byte $EE                   ; INC abs
         .byte ptr1+1                ; 10
         .byte $00
         rts                         ; 16
:        nop                         ; 7
         bit $FF                     ; 10
         rts                         ; 16
.endproc

; Total cost 26 cycles
.proc set_target
         lda sound_levels+0,x        ; 4
         sta target+1+0              ; 7
         lda sound_levels+1,x        ; 11
         sta target+1+1              ; 14
         rts                         ; 20
.endproc

waste_42: nop
waste_40: nop
waste_38: nop
waste_36: nop
waste_34: nop
waste_32: nop
waste_30: nop
waste_28: nop
waste_26: nop
waste_24: nop
waste_22: nop
waste_20: nop
waste_18: nop
waste_16: nop
waste_14: nop
waste_12: rts


waste_43: nop
waste_41: nop
waste_39: nop
waste_37: nop
waste_35: nop
waste_33: nop
waste_31: nop
waste_29: nop
waste_27: nop
waste_25: nop
waste_23: nop
waste_21: nop
waste_19: nop
waste_17: nop
waste_15: bit $FF
          rts

.proc _a2_sample_play
         php
         sei
         sta ptr1
         stx ptr1+1
         ora ptr1+1
         bne :+
         plp
         rts
:        lda #$4C
         sta target
         ldy ptr1
         lda #$00
         sta ptr1
         lda (ptr1),y
         tax
         jsr set_target
         jsr incr_pointer
         jmp target
.endproc

.proc play_done
         plp
         rts
.endproc

.assert <* > $32, error ; for the page crosser
.proc sound_levels_off
         .addr sound_level_0_0
         .addr sound_level_1_0
         .addr sound_level_2_0
         .addr sound_level_3_0
         .addr sound_level_4_0
         .addr sound_level_5_0
         .addr sound_level_6_0
         .addr sound_level_7_0
         .addr sound_level_8_0
         .addr sound_level_9_0
         .addr sound_level_10_0
         .addr sound_level_11_0
         .addr sound_level_12_0
         .addr sound_level_13_0
         .addr sound_level_14_0
         .addr sound_level_15_0
         .addr sound_level_16_0
         .addr sound_level_17_0
         .addr sound_level_18_0
         .addr sound_level_19_0
         .addr sound_level_20_0
         .addr sound_level_21_0
         .addr sound_level_22_0
         .addr sound_level_23_0
         .addr sound_level_24_0
         .addr sound_level_25_0
         .addr sound_level_26_0
         .addr sound_level_27_0
         .addr sound_level_28_0
         .addr sound_level_29_0
         .addr sound_level_30_0
         .addr sound_level_31_0
         .addr sound_level_32_0
         .addr sound_level_33_0
         .addr sound_level_34_0
         .addr sound_level_35_0
         .addr sound_level_36_0
         .addr sound_level_37_0
         .addr sound_level_38_0
         .addr sound_level_39_0
         .addr sound_level_40_0
         .addr sound_level_41_0
         .addr sound_level_42_0
         .addr sound_level_43_0
         .addr sound_level_44_0
         .addr sound_level_45_0
         .addr sound_level_46_0
         .addr sound_level_47_0
         .addr play_done
.endproc

sound_levels = sound_levels_off - $32
SPKR_OFF = SPKR - $32
sound_player_end_header = *
.assert >START_SOUND_PLAYER = >*, error
; 0 cycles available between speaker access,
; 55 cycles available after speaker access.
.proc sound_level_0_0
         sta SPKR                           ; 4 cycles, 59 remain
         sta SPKR                           ; 4 cycles, 55 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 48 remain
         jsr set_target                     ; 26 cycles, 22 remain
         jsr incr_pointer                   ; 22 cycles, 0 remain
.endproc
.proc sound_level_0_1
         sta SPKR                           ; 4 cycles, 59 remain
         sta SPKR                           ; 4 cycles, 55 remain
         jsr waste_43                       ; 43 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 1 cycles available between speaker access,
; 54 cycles available after speaker access.
.proc sound_level_1_0
         sta SPKR                           ; 4 cycles, 59 remain
         sta SPKR_OFF,x                     ; 5 cycles, 54 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 47 remain
         stx tmp3
         ldx #$32+2                         ; 5 cycles, 42 remain
         jsr incr_pointer                   ; 22 cycles, 20 remain
         jsr waste_20                       ; 20 cycles, 0 remain
.endproc
.proc sound_level_1_1
         sta SPKR                           ; 4 cycles, 59 remain
         sta SPKR_OFF,x                     ; 5 cycles, 54 remain
         ldx tmp3                           ; 3 cycles, 51 remain
         jsr set_target                     ; 26 cycles, 25 remain
         jsr waste_19                       ; 19 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 2 cycles available between speaker access,
; 53 cycles available after speaker access.
.proc sound_level_2_0
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         sta SPKR                           ; 4 cycles, 53 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 46 remain
         jsr set_target                     ; 26 cycles, 20 remain
         jsr waste_20                       ; 20 cycles, 0 remain
.endproc
.proc sound_level_2_1
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         sta SPKR                           ; 4 cycles, 53 remain
         jsr incr_pointer                   ; 22 cycles, 31 remain
         jsr waste_25                       ; 25 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 3 cycles available between speaker access,
; 52 cycles available after speaker access.
.proc sound_level_3_0
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         sta SPKR                           ; 4 cycles, 52 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 45 remain
         jsr set_target                     ; 26 cycles, 19 remain
         jsr waste_19                       ; 19 cycles, 0 remain
.endproc
.proc sound_level_3_1
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         sta SPKR                           ; 4 cycles, 52 remain
         jsr incr_pointer                   ; 22 cycles, 30 remain
         jsr waste_24                       ; 24 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 4 cycles available between speaker access,
; 51 cycles available after speaker access.
.proc sound_level_4_0
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         sta SPKR                           ; 4 cycles, 51 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 44 remain
         jsr set_target                     ; 26 cycles, 18 remain
         jsr waste_18                       ; 18 cycles, 0 remain
.endproc
.proc sound_level_4_1
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         sta SPKR                           ; 4 cycles, 51 remain
         jsr incr_pointer                   ; 22 cycles, 29 remain
         jsr waste_23                       ; 23 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 5 cycles available between speaker access,
; 50 cycles available after speaker access.
.proc sound_level_5_0
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         nop                                ; 2 cycles, 54 remain
         sta SPKR                           ; 4 cycles, 50 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 43 remain
         jsr set_target                     ; 26 cycles, 17 remain
         jsr waste_17                       ; 17 cycles, 0 remain
.endproc
.proc sound_level_5_1
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         nop                                ; 2 cycles, 54 remain
         sta SPKR                           ; 4 cycles, 50 remain
         jsr incr_pointer                   ; 22 cycles, 28 remain
         jsr waste_22                       ; 22 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 6 cycles available between speaker access,
; 49 cycles available after speaker access.
.proc sound_level_6_0
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         nop                                ; 2 cycles, 53 remain
         sta SPKR                           ; 4 cycles, 49 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 42 remain
         jsr set_target                     ; 26 cycles, 16 remain
         jsr waste_16                       ; 16 cycles, 0 remain
.endproc
.proc sound_level_6_1
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         nop                                ; 2 cycles, 53 remain
         sta SPKR                           ; 4 cycles, 49 remain
         jsr incr_pointer                   ; 22 cycles, 27 remain
         jsr waste_21                       ; 21 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 7 cycles available between speaker access,
; 48 cycles available after speaker access.
.proc sound_level_7_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         sta SPKR                           ; 4 cycles, 48 remain
         jsr set_target                     ; 26 cycles, 22 remain
         jsr incr_pointer                   ; 22 cycles, 0 remain
.endproc
.proc sound_level_7_1
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         nop                                ; 2 cycles, 54 remain
         nop                                ; 2 cycles, 52 remain
         sta SPKR                           ; 4 cycles, 48 remain
         jsr waste_42                       ; 42 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 8 cycles available between speaker access,
; 47 cycles available after speaker access.
.proc sound_level_8_0
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         nop                                ; 2 cycles, 53 remain
         nop                                ; 2 cycles, 51 remain
         sta SPKR                           ; 4 cycles, 47 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 40 remain
         jsr set_target                     ; 26 cycles, 14 remain
         jsr waste_14                       ; 14 cycles, 0 remain
.endproc
.proc sound_level_8_1
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         nop                                ; 2 cycles, 53 remain
         nop                                ; 2 cycles, 51 remain
         sta SPKR                           ; 4 cycles, 47 remain
         jsr incr_pointer                   ; 22 cycles, 25 remain
         jsr waste_19                       ; 19 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 9 cycles available between speaker access,
; 46 cycles available after speaker access.
.proc sound_level_9_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         sta SPKR                           ; 4 cycles, 46 remain
         jsr set_target                     ; 26 cycles, 20 remain
         jsr waste_20                       ; 20 cycles, 0 remain
.endproc
.proc sound_level_9_1
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         nop                                ; 2 cycles, 54 remain
         nop                                ; 2 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         sta SPKR                           ; 4 cycles, 46 remain
         jsr incr_pointer                   ; 22 cycles, 24 remain
         jsr waste_18                       ; 18 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 10 cycles available between speaker access,
; 45 cycles available after speaker access.
.proc sound_level_10_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         bit $FF                            ; 3 cycles, 49 remain
         sta SPKR                           ; 4 cycles, 45 remain
         jsr set_target                     ; 26 cycles, 19 remain
         jsr waste_19                       ; 19 cycles, 0 remain
.endproc
.proc sound_level_10_1
         sta SPKR                           ; 4 cycles, 59 remain
         nop                                ; 2 cycles, 57 remain
         nop                                ; 2 cycles, 55 remain
         nop                                ; 2 cycles, 53 remain
         nop                                ; 2 cycles, 51 remain
         nop                                ; 2 cycles, 49 remain
         sta SPKR                           ; 4 cycles, 45 remain
         jsr incr_pointer                   ; 22 cycles, 23 remain
         jsr waste_17                       ; 17 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 11 cycles available between speaker access,
; 44 cycles available after speaker access.
.proc sound_level_11_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         nop                                ; 2 cycles, 48 remain
         sta SPKR                           ; 4 cycles, 44 remain
         jsr set_target                     ; 26 cycles, 18 remain
         jsr waste_18                       ; 18 cycles, 0 remain
.endproc
.proc sound_level_11_1
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         nop                                ; 2 cycles, 54 remain
         nop                                ; 2 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         nop                                ; 2 cycles, 48 remain
         sta SPKR                           ; 4 cycles, 44 remain
         jsr incr_pointer                   ; 22 cycles, 22 remain
         jsr waste_16                       ; 16 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 12 cycles available between speaker access,
; 43 cycles available after speaker access.
.proc sound_level_12_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         bit $FF                            ; 3 cycles, 49 remain
         nop                                ; 2 cycles, 47 remain
         sta SPKR                           ; 4 cycles, 43 remain
         jsr set_target                     ; 26 cycles, 17 remain
         jsr waste_17                       ; 17 cycles, 0 remain
.endproc
.proc sound_level_12_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_12                       ; 12 cycles, 47 remain
         sta SPKR                           ; 4 cycles, 43 remain
         jsr incr_pointer                   ; 22 cycles, 21 remain
         jsr waste_15                       ; 15 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 13 cycles available between speaker access,
; 42 cycles available after speaker access.
.proc sound_level_13_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         nop                                ; 2 cycles, 48 remain
         nop                                ; 2 cycles, 46 remain
         sta SPKR                           ; 4 cycles, 42 remain
         jsr set_target                     ; 26 cycles, 16 remain
         jsr waste_16                       ; 16 cycles, 0 remain
.endproc
.proc sound_level_13_1
         sta SPKR                           ; 4 cycles, 59 remain
         bit $FF                            ; 3 cycles, 56 remain
         nop                                ; 2 cycles, 54 remain
         nop                                ; 2 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         nop                                ; 2 cycles, 48 remain
         nop                                ; 2 cycles, 46 remain
         sta SPKR                           ; 4 cycles, 42 remain
         jsr incr_pointer                   ; 22 cycles, 20 remain
         jsr waste_14                       ; 14 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 14 cycles available between speaker access,
; 41 cycles available after speaker access.
.proc sound_level_14_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         bit $FF                            ; 3 cycles, 49 remain
         nop                                ; 2 cycles, 47 remain
         nop                                ; 2 cycles, 45 remain
         sta SPKR                           ; 4 cycles, 41 remain
         jsr set_target                     ; 26 cycles, 15 remain
         jsr waste_15                       ; 15 cycles, 0 remain
.endproc
.proc sound_level_14_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_14                       ; 14 cycles, 45 remain
         sta SPKR                           ; 4 cycles, 41 remain
         jsr incr_pointer                   ; 22 cycles, 19 remain
         bit $FF                            ; 3 cycles, 16 remain
         nop                                ; 2 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 15 cycles available between speaker access,
; 40 cycles available after speaker access.
.proc sound_level_15_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         nop                                ; 2 cycles, 48 remain
         nop                                ; 2 cycles, 46 remain
         nop                                ; 2 cycles, 44 remain
         sta SPKR                           ; 4 cycles, 40 remain
         jsr set_target                     ; 26 cycles, 14 remain
         jsr waste_14                       ; 14 cycles, 0 remain
.endproc
.proc sound_level_15_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_15                       ; 15 cycles, 44 remain
         sta SPKR                           ; 4 cycles, 40 remain
         jsr incr_pointer                   ; 22 cycles, 18 remain
         jsr waste_12                       ; 12 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 16 cycles available between speaker access,
; 39 cycles available after speaker access.
.proc sound_level_16_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         bit $FF                            ; 3 cycles, 49 remain
         nop                                ; 2 cycles, 47 remain
         nop                                ; 2 cycles, 45 remain
         nop                                ; 2 cycles, 43 remain
         sta SPKR                           ; 4 cycles, 39 remain
         jsr set_target                     ; 26 cycles, 13 remain
         bit $FF                            ; 3 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_16_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_16                       ; 16 cycles, 43 remain
         sta SPKR                           ; 4 cycles, 39 remain
         jsr incr_pointer                   ; 22 cycles, 17 remain
         bit $FF                            ; 3 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 17 cycles available between speaker access,
; 38 cycles available after speaker access.
.proc sound_level_17_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         nop                                ; 2 cycles, 50 remain
         nop                                ; 2 cycles, 48 remain
         nop                                ; 2 cycles, 46 remain
         nop                                ; 2 cycles, 44 remain
         nop                                ; 2 cycles, 42 remain
         sta SPKR                           ; 4 cycles, 38 remain
         jsr set_target                     ; 26 cycles, 12 remain
         jsr waste_12                       ; 12 cycles, 0 remain
.endproc
.proc sound_level_17_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_17                       ; 17 cycles, 42 remain
         sta SPKR                           ; 4 cycles, 38 remain
         jsr incr_pointer                   ; 22 cycles, 16 remain
         nop                                ; 2 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 18 cycles available between speaker access,
; 37 cycles available after speaker access.
.proc sound_level_18_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         bit $FF                            ; 3 cycles, 49 remain
         nop                                ; 2 cycles, 47 remain
         nop                                ; 2 cycles, 45 remain
         nop                                ; 2 cycles, 43 remain
         nop                                ; 2 cycles, 41 remain
         sta SPKR                           ; 4 cycles, 37 remain
         jsr set_target                     ; 26 cycles, 11 remain
         bit $FF                            ; 3 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_18_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_18                       ; 18 cycles, 41 remain
         sta SPKR                           ; 4 cycles, 37 remain
         jsr incr_pointer                   ; 22 cycles, 15 remain
         bit $FF                            ; 3 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 19 cycles available between speaker access,
; 36 cycles available after speaker access.
.proc sound_level_19_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_12                       ; 12 cycles, 40 remain
         sta SPKR                           ; 4 cycles, 36 remain
         jsr set_target                     ; 26 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_19_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_19                       ; 19 cycles, 40 remain
         sta SPKR                           ; 4 cycles, 36 remain
         jsr incr_pointer                   ; 22 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 20 cycles available between speaker access,
; 35 cycles available after speaker access.
.proc sound_level_20_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         bit $FF                            ; 3 cycles, 49 remain
         nop                                ; 2 cycles, 47 remain
         nop                                ; 2 cycles, 45 remain
         nop                                ; 2 cycles, 43 remain
         nop                                ; 2 cycles, 41 remain
         nop                                ; 2 cycles, 39 remain
         sta SPKR                           ; 4 cycles, 35 remain
         jsr set_target                     ; 26 cycles, 9 remain
         bit $FF                            ; 3 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_20_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_20                       ; 20 cycles, 39 remain
         sta SPKR                           ; 4 cycles, 35 remain
         jsr incr_pointer                   ; 22 cycles, 13 remain
         bit $FF                            ; 3 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 21 cycles available between speaker access,
; 34 cycles available after speaker access.
.proc sound_level_21_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_14                       ; 14 cycles, 38 remain
         sta SPKR                           ; 4 cycles, 34 remain
         jsr set_target                     ; 26 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_21_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_21                       ; 21 cycles, 38 remain
         sta SPKR                           ; 4 cycles, 34 remain
         jsr incr_pointer                   ; 22 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 22 cycles available between speaker access,
; 33 cycles available after speaker access.
.proc sound_level_22_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_15                       ; 15 cycles, 37 remain
         sta SPKR                           ; 4 cycles, 33 remain
         jsr set_target                     ; 26 cycles, 7 remain
         bit $FF                            ; 3 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_22_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         sta SPKR                           ; 4 cycles, 33 remain
         jsr waste_27                       ; 27 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 23 cycles available between speaker access,
; 32 cycles available after speaker access.
.proc sound_level_23_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_16                       ; 16 cycles, 36 remain
         sta SPKR                           ; 4 cycles, 32 remain
         jsr set_target                     ; 26 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_23_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_23                       ; 23 cycles, 36 remain
         sta SPKR                           ; 4 cycles, 32 remain
         jsr incr_pointer                   ; 22 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 24 cycles available between speaker access,
; 31 cycles available after speaker access.
.proc sound_level_24_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_17                       ; 17 cycles, 35 remain
         sta SPKR                           ; 4 cycles, 31 remain
         jsr set_target                     ; 26 cycles, 5 remain
         bit $FF                            ; 3 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_24_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         nop                                ; 2 cycles, 35 remain
         sta SPKR                           ; 4 cycles, 31 remain
         jsr waste_25                       ; 25 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 25 cycles available between speaker access,
; 30 cycles available after speaker access.
.proc sound_level_25_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_18                       ; 18 cycles, 34 remain
         sta SPKR                           ; 4 cycles, 30 remain
         jsr set_target                     ; 26 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_25_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         bit $FF                            ; 3 cycles, 34 remain
         sta SPKR                           ; 4 cycles, 30 remain
         jsr waste_24                       ; 24 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 26 cycles available between speaker access,
; 29 cycles available after speaker access.
.proc sound_level_26_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_19                       ; 19 cycles, 33 remain
         sta SPKR                           ; 4 cycles, 29 remain
         jsr set_target                     ; 26 cycles, 3 remain
         bit $FF                            ; 3 cycles, 0 remain
.endproc
.proc sound_level_26_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         nop                                ; 2 cycles, 35 remain
         nop                                ; 2 cycles, 33 remain
         sta SPKR                           ; 4 cycles, 29 remain
         jsr waste_23                       ; 23 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 27 cycles available between speaker access,
; 28 cycles available after speaker access.
.proc sound_level_27_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_20                       ; 20 cycles, 32 remain
         sta SPKR                           ; 4 cycles, 28 remain
         jsr set_target                     ; 26 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_27_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         bit $FF                            ; 3 cycles, 34 remain
         nop                                ; 2 cycles, 32 remain
         sta SPKR                           ; 4 cycles, 28 remain
         jsr waste_22                       ; 22 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 28 cycles available between speaker access,
; 27 cycles available after speaker access.
.proc sound_level_28_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_21                       ; 21 cycles, 31 remain
         sta SPKR                           ; 4 cycles, 27 remain
         jsr incr_pointer                   ; 22 cycles, 5 remain
         bit $FF                            ; 3 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_28_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr set_target                     ; 26 cycles, 33 remain
         nop                                ; 2 cycles, 31 remain
         sta SPKR                           ; 4 cycles, 27 remain
         jsr waste_21                       ; 21 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 29 cycles available between speaker access,
; 26 cycles available after speaker access.
.proc sound_level_29_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr incr_pointer                   ; 22 cycles, 30 remain
         sta SPKR                           ; 4 cycles, 26 remain
         jsr set_target                     ; 26 cycles, 0 remain
.endproc
.proc sound_level_29_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_29                       ; 29 cycles, 30 remain
         sta SPKR                           ; 4 cycles, 26 remain
         jsr waste_20                       ; 20 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 30 cycles available between speaker access,
; 25 cycles available after speaker access.
.proc sound_level_30_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr waste_23                       ; 23 cycles, 29 remain
         sta SPKR                           ; 4 cycles, 25 remain
         jsr incr_pointer                   ; 22 cycles, 3 remain
         bit $FF                            ; 3 cycles, 0 remain
.endproc
.proc sound_level_30_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr set_target                     ; 26 cycles, 33 remain
         nop                                ; 2 cycles, 31 remain
         nop                                ; 2 cycles, 29 remain
         sta SPKR                           ; 4 cycles, 25 remain
         jsr waste_19                       ; 19 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 31 cycles available between speaker access,
; 24 cycles available after speaker access.
.proc sound_level_31_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr incr_pointer                   ; 22 cycles, 30 remain
         nop                                ; 2 cycles, 28 remain
         sta SPKR                           ; 4 cycles, 24 remain
         jsr waste_24                       ; 24 cycles, 0 remain
.endproc
.proc sound_level_31_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr set_target                     ; 26 cycles, 33 remain
         bit $FF                            ; 3 cycles, 30 remain
         nop                                ; 2 cycles, 28 remain
         sta SPKR                           ; 4 cycles, 24 remain
         jsr waste_18                       ; 18 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 32 cycles available between speaker access,
; 23 cycles available after speaker access.
.proc sound_level_32_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr incr_pointer                   ; 22 cycles, 30 remain
         bit $FF                            ; 3 cycles, 27 remain
         sta SPKR                           ; 4 cycles, 23 remain
         jsr waste_23                       ; 23 cycles, 0 remain
.endproc
.proc sound_level_32_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr set_target                     ; 26 cycles, 33 remain
         nop                                ; 2 cycles, 31 remain
         nop                                ; 2 cycles, 29 remain
         nop                                ; 2 cycles, 27 remain
         sta SPKR                           ; 4 cycles, 23 remain
         jsr waste_17                       ; 17 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 33 cycles available between speaker access,
; 22 cycles available after speaker access.
.proc sound_level_33_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         sta SPKR                           ; 4 cycles, 22 remain
         jsr incr_pointer                   ; 22 cycles, 0 remain
.endproc
.proc sound_level_33_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr waste_33                       ; 33 cycles, 26 remain
         sta SPKR                           ; 4 cycles, 22 remain
         jsr waste_16                       ; 16 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 34 cycles available between speaker access,
; 21 cycles available after speaker access.
.proc sound_level_34_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr incr_pointer                   ; 22 cycles, 30 remain
         bit $FF                            ; 3 cycles, 27 remain
         nop                                ; 2 cycles, 25 remain
         sta SPKR                           ; 4 cycles, 21 remain
         jsr waste_21                       ; 21 cycles, 0 remain
.endproc
.proc sound_level_34_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr set_target                     ; 26 cycles, 33 remain
         nop                                ; 2 cycles, 31 remain
         nop                                ; 2 cycles, 29 remain
         nop                                ; 2 cycles, 27 remain
         nop                                ; 2 cycles, 25 remain
         sta SPKR                           ; 4 cycles, 21 remain
         jsr waste_15                       ; 15 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 35 cycles available between speaker access,
; 20 cycles available after speaker access.
.proc sound_level_35_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         nop                                ; 2 cycles, 24 remain
         sta SPKR                           ; 4 cycles, 20 remain
         jsr waste_20                       ; 20 cycles, 0 remain
.endproc
.proc sound_level_35_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         bit $FF                            ; 3 cycles, 34 remain
         nop                                ; 2 cycles, 32 remain
         nop                                ; 2 cycles, 30 remain
         nop                                ; 2 cycles, 28 remain
         nop                                ; 2 cycles, 26 remain
         nop                                ; 2 cycles, 24 remain
         sta SPKR                           ; 4 cycles, 20 remain
         jsr waste_14                       ; 14 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 36 cycles available between speaker access,
; 19 cycles available after speaker access.
.proc sound_level_36_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         bit $FF                            ; 3 cycles, 23 remain
         sta SPKR                           ; 4 cycles, 19 remain
         jsr waste_19                       ; 19 cycles, 0 remain
.endproc
.proc sound_level_36_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_14                       ; 14 cycles, 23 remain
         sta SPKR                           ; 4 cycles, 19 remain
         bit $FF                            ; 3 cycles, 16 remain
         nop                                ; 2 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 37 cycles available between speaker access,
; 18 cycles available after speaker access.
.proc sound_level_37_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         nop                                ; 2 cycles, 24 remain
         nop                                ; 2 cycles, 22 remain
         sta SPKR                           ; 4 cycles, 18 remain
         jsr waste_18                       ; 18 cycles, 0 remain
.endproc
.proc sound_level_37_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_15                       ; 15 cycles, 22 remain
         sta SPKR                           ; 4 cycles, 18 remain
         jsr waste_12                       ; 12 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 38 cycles available between speaker access,
; 17 cycles available after speaker access.
.proc sound_level_38_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         bit $FF                            ; 3 cycles, 23 remain
         nop                                ; 2 cycles, 21 remain
         sta SPKR                           ; 4 cycles, 17 remain
         jsr waste_17                       ; 17 cycles, 0 remain
.endproc
.proc sound_level_38_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_16                       ; 16 cycles, 21 remain
         sta SPKR                           ; 4 cycles, 17 remain
         bit $FF                            ; 3 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 39 cycles available between speaker access,
; 16 cycles available after speaker access.
.proc sound_level_39_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         nop                                ; 2 cycles, 24 remain
         nop                                ; 2 cycles, 22 remain
         nop                                ; 2 cycles, 20 remain
         sta SPKR                           ; 4 cycles, 16 remain
         jsr waste_16                       ; 16 cycles, 0 remain
.endproc
.proc sound_level_39_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_17                       ; 17 cycles, 20 remain
         sta SPKR                           ; 4 cycles, 16 remain
         nop                                ; 2 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 40 cycles available between speaker access,
; 15 cycles available after speaker access.
.proc sound_level_40_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         bit $FF                            ; 3 cycles, 23 remain
         nop                                ; 2 cycles, 21 remain
         nop                                ; 2 cycles, 19 remain
         sta SPKR                           ; 4 cycles, 15 remain
         jsr waste_15                       ; 15 cycles, 0 remain
.endproc
.proc sound_level_40_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_18                       ; 18 cycles, 19 remain
         sta SPKR                           ; 4 cycles, 15 remain
         bit $FF                            ; 3 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 41 cycles available between speaker access,
; 14 cycles available after speaker access.
.proc sound_level_41_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         nop                                ; 2 cycles, 24 remain
         nop                                ; 2 cycles, 22 remain
         nop                                ; 2 cycles, 20 remain
         nop                                ; 2 cycles, 18 remain
         sta SPKR                           ; 4 cycles, 14 remain
         jsr waste_14                       ; 14 cycles, 0 remain
.endproc
.proc sound_level_41_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_19                       ; 19 cycles, 18 remain
         sta SPKR                           ; 4 cycles, 14 remain
         nop                                ; 2 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 42 cycles available between speaker access,
; 13 cycles available after speaker access.
.proc sound_level_42_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         bit $FF                            ; 3 cycles, 23 remain
         nop                                ; 2 cycles, 21 remain
         nop                                ; 2 cycles, 19 remain
         nop                                ; 2 cycles, 17 remain
         sta SPKR                           ; 4 cycles, 13 remain
         bit $FF                            ; 3 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_42_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_20                       ; 20 cycles, 17 remain
         sta SPKR                           ; 4 cycles, 13 remain
         bit $FF                            ; 3 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 43 cycles available between speaker access,
; 12 cycles available after speaker access.
.proc sound_level_43_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         nop                                ; 2 cycles, 24 remain
         nop                                ; 2 cycles, 22 remain
         nop                                ; 2 cycles, 20 remain
         nop                                ; 2 cycles, 18 remain
         nop                                ; 2 cycles, 16 remain
         sta SPKR                           ; 4 cycles, 12 remain
         jsr waste_12                       ; 12 cycles, 0 remain
.endproc
.proc sound_level_43_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_21                       ; 21 cycles, 16 remain
         sta SPKR                           ; 4 cycles, 12 remain
         nop                                ; 2 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 44 cycles available between speaker access,
; 11 cycles available after speaker access.
.proc sound_level_44_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         bit $FF                            ; 3 cycles, 23 remain
         nop                                ; 2 cycles, 21 remain
         nop                                ; 2 cycles, 19 remain
         nop                                ; 2 cycles, 17 remain
         nop                                ; 2 cycles, 15 remain
         sta SPKR                           ; 4 cycles, 11 remain
         bit $FF                            ; 3 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_44_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_22                       ; 22 cycles, 15 remain
         sta SPKR                           ; 4 cycles, 11 remain
         bit $FF                            ; 3 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 45 cycles available between speaker access,
; 10 cycles available after speaker access.
.proc sound_level_45_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         jsr waste_12                       ; 12 cycles, 14 remain
         sta SPKR                           ; 4 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_45_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_23                       ; 23 cycles, 14 remain
         sta SPKR                           ; 4 cycles, 10 remain
         nop                                ; 2 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 46 cycles available between speaker access,
; 9 cycles available after speaker access.
.proc sound_level_46_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         bit $FF                            ; 3 cycles, 23 remain
         nop                                ; 2 cycles, 21 remain
         nop                                ; 2 cycles, 19 remain
         nop                                ; 2 cycles, 17 remain
         nop                                ; 2 cycles, 15 remain
         nop                                ; 2 cycles, 13 remain
         sta SPKR                           ; 4 cycles, 9 remain
         bit $FF                            ; 3 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_46_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_24                       ; 24 cycles, 13 remain
         sta SPKR                           ; 4 cycles, 9 remain
         bit $FF                            ; 3 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc


; 47 cycles available between speaker access,
; 8 cycles available after speaker access.
.proc sound_level_47_0
         sta SPKR                           ; 4 cycles, 59 remain
         lda (ptr1),y
         tax                                ; 7 cycles, 52 remain
         jsr set_target                     ; 26 cycles, 26 remain
         jsr waste_14                       ; 14 cycles, 12 remain
         sta SPKR                           ; 4 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         nop                                ; 2 cycles, 4 remain
         nop                                ; 2 cycles, 2 remain
         nop                                ; 2 cycles, 0 remain
.endproc
.proc sound_level_47_1
         sta SPKR                           ; 4 cycles, 59 remain
         jsr incr_pointer                   ; 22 cycles, 37 remain
         jsr waste_25                       ; 25 cycles, 12 remain
         sta SPKR                           ; 4 cycles, 8 remain
         nop                                ; 2 cycles, 6 remain
         jmp target                         ; 6 cycles, 0 remain
.endproc
